CREATE TABLE `user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(126) NOT NULL,
  `PASSWORD` VARCHAR(126) NOT NULL,
  `EMAIL` VARCHAR(126) DEFAULT NULL,
  `FIRST_NAME` VARCHAR(126) DEFAULT NULL,
  `LAST_NAME` VARCHAR(126) DEFAULT NULL,
  `GENDER` VARCHAR(50) DEFAULT NULL,
  `STATUS` VARCHAR(10) DEFAULT NULL,
  `DATE_OF_BIRTH` DATE DEFAULT NULL,
  `CREATED_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=INNODB AUTO_INCREMENT = 1001 DEFAULT CHARSET=utf8;


CREATE TABLE `catalog` (
  `CATALOG_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(254) NOT NULL,
  `DESCRIPTION` VARCHAR(254) DEFAULT NULL,
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  PRIMARY KEY (`CATALOG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=2001 DEFAULT CHARSET=utf8;


CREATE TABLE `catgroup` (
  `CATGROUP_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(254) NOT NULL,
  `DESCRIPTION` VARCHAR(254) DEFAULT NULL,
  `LONGDESCRIPTION` VARCHAR(512) DEFAULT NULL,
  `THUMBNAIL` VARCHAR(254) DEFAULT NULL,
  `FULLIMAGE` VARCHAR(254) DEFAULT NULL,
  `MARKFORDELETE` INT(11) NOT NULL,
  `LASTUPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD3` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`CATGROUP_ID`)
) ENGINE=INNODB AUTO_INCREMENT=3001 DEFAULT CHARSET=utf8;


CREATE TABLE `cattogrp` (
  `CATGROUP_ID` BIGINT(20) NOT NULL,
  `CATALOG_ID` BIGINT(20) NOT NULL,
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  KEY `CATGROUP_ID` (`CATGROUP_ID`),
  KEY `CATALOG_ID` (`CATALOG_ID`),
  FOREIGN KEY (`CATGROUP_ID`) REFERENCES `catgroup` (`CATGROUP_ID`),
  FOREIGN KEY (`CATALOG_ID`) REFERENCES `catalog` (`CATALOG_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `catentry` (
  `CATENTRY_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CHNUMBER` VARCHAR(64) NOT NULL,
  `CHNAME` VARCHAR(128) NOT NULL,
  `MARKFORDELETE` INT(11) NOT NULL,
  `URL` VARCHAR(254) DEFAULT NULL,
  `LASTUPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `BUYABLE` INT(11) DEFAULT NULL,
  `STARTDATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ENDDATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AVAILABILITYDATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DISCONTINUEDATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD3` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`CATENTRY_ID`),
  UNIQUE KEY `CHNUMBER` (`CHNUMBER`)
) ENGINE=INNODB AUTO_INCREMENT=4001 DEFAULT CHARSET=utf8;

CREATE TABLE `catgpenrel` (
  `CATGROUP_ID` BIGINT(20) NOT NULL,
  `CATENTRY_ID` BIGINT(20) NOT NULL,
  `CATALOG_ID` BIGINT(20) NOT NULL,
  `LASTUPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD3` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`CATGROUP_ID`,`CATENTRY_ID`,`CATALOG_ID`),
  KEY `CATENTRY_ID` (`CATENTRY_ID`),
  KEY `CATALOG_ID` (`CATALOG_ID`),
  FOREIGN KEY (`CATGROUP_ID`) REFERENCES `catgroup` (`CATGROUP_ID`),
  FOREIGN KEY (`CATENTRY_ID`) REFERENCES `catentry` (`CATENTRY_ID`),
  FOREIGN KEY (`CATALOG_ID`) REFERENCES `catalog` (`CATALOG_ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;




CREATE TABLE `orders` (
  `ORDERS_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `TOTALPRODUCT` DECIMAL(20,5) NOT NULL,
  `TOTALTAX` DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
  `DESCRIPTION` VARCHAR(254) DEFAULT NULL,
  `TIMEPLACED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTUPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` CHAR(3) NOT NULL,
  `USERS_ID` BIGINT(20) NOT NULL,
  `TOTALADJUSTMENT` DECIMAL(20,5) NOT NULL DEFAULT '0.00000',
  `CSR_USERS_ID` BIGINT(20) DEFAULT NULL,
  `EXPIREDATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD3` VARCHAR(254) DEFAULT NULL,
  PRIMARY KEY (`ORDERS_ID`),
  FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5001 DEFAULT CHARSET=utf8;


CREATE TABLE `suborders` (
  `SUBORDERS_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ORDERS_ID` BIGINT(20) NOT NULL,
  `TOTALPRODUCT` DECIMAL(20,5) NOT NULL,
  `TOTALTAX` DECIMAL(20,5) NOT NULL,
  `CURRENCY` CHAR(10) DEFAULT NULL,
  `DESCRIPTION` VARCHAR(254) DEFAULT NULL,
  `TIMEPLACED` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTUPDATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` CHAR(3) NOT NULL,
  `USERS_ID` BIGINT(20) NOT NULL,
  `TOTALADJUSTMENT` DECIMAL(20,5) NOT NULL,
  `EXPIREDATE` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` INT(11) DEFAULT NULL,
  `FIELD2` VARCHAR(128) DEFAULT NULL,
  `FIELD3` VARCHAR(254) DEFAULT NULL,
  PRIMARY KEY (`SUBORDERS_ID`),
  KEY `ORDERS_ID` (`ORDERS_ID`),
  KEY `USERS_ID` (`USERS_ID`),
  FOREIGN KEY (`ORDERS_ID`) REFERENCES `orders` (`ORDERS_ID`),
  FOREIGN KEY (`USERS_ID`) REFERENCES `users` (`USERS_ID`)
) ENGINE=INNODB AUTO_INCREMENT=6001 DEFAULT CHARSET=utf8;






