/*
SQLyog Community v11.31 (32 bit)
MySQL - 5.5.48 : Database - lco_db
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
USE `lco_db`;

/*Table structure for table `catalog` */

DROP TABLE IF EXISTS `catalog`;

CREATE TABLE `catalog` (
  `CATALOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(254) NOT NULL,
  `DESCRIPTION` varchar(254) DEFAULT NULL,
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`CATALOG_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2002 DEFAULT CHARSET=utf8;

/*Table structure for table `catentry` */

DROP TABLE IF EXISTS `catentry`;

CREATE TABLE `catentry` (
  `CATENTRY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CHNUMBER` varchar(64) NOT NULL,
  `CHNAME` varchar(128) NOT NULL,
  `MARKFORDELETE` int(11) NOT NULL,
  `URL` varchar(254) DEFAULT NULL,
  `LASTUPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `BUYABLE` int(11) DEFAULT NULL,
  `STARTDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ENDDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `AVAILABILITYDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `DISCONTINUEDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`CATENTRY_ID`),
  UNIQUE KEY `CHNUMBER` (`CHNUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=4034 DEFAULT CHARSET=utf8;

/*Table structure for table `catgpenrel` */

DROP TABLE IF EXISTS `catgpenrel`;

CREATE TABLE `catgpenrel` (
  `CATGROUP_ID` bigint(20) NOT NULL,
  `CATENTRY_ID` bigint(20) NOT NULL,
  `CATALOG_ID` bigint(20) NOT NULL,
  `LASTUPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`CATGROUP_ID`,`CATENTRY_ID`,`CATALOG_ID`),
  KEY `CATENTRY_ID` (`CATENTRY_ID`),
  KEY `CATALOG_ID` (`CATALOG_ID`),
  CONSTRAINT `catgpenrel_ibfk_1` FOREIGN KEY (`CATGROUP_ID`) REFERENCES `catgroup` (`CATGROUP_ID`),
  CONSTRAINT `catgpenrel_ibfk_2` FOREIGN KEY (`CATENTRY_ID`) REFERENCES `catentry` (`CATENTRY_ID`),
  CONSTRAINT `catgpenrel_ibfk_3` FOREIGN KEY (`CATALOG_ID`) REFERENCES `catalog` (`CATALOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `catgroup` */

DROP TABLE IF EXISTS `catgroup`;

CREATE TABLE `catgroup` (
  `CATGROUP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(254) NOT NULL,
  `DESCRIPTION` varchar(254) DEFAULT NULL,
  `LONGDESCRIPTION` varchar(512) DEFAULT NULL,
  `THUMBNAIL` varchar(254) DEFAULT NULL,
  `FULLIMAGE` varchar(254) DEFAULT NULL,
  `MARKFORDELETE` int(11) NOT NULL,
  `LASTUPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`CATGROUP_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3014 DEFAULT CHARSET=utf8;

/*Table structure for table `cattogrp` */

DROP TABLE IF EXISTS `cattogrp`;

CREATE TABLE `cattogrp` (
  `CATGROUP_ID` bigint(20) NOT NULL,
  `CATALOG_ID` bigint(20) NOT NULL,
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  KEY `CATGROUP_ID` (`CATGROUP_ID`),
  KEY `CATALOG_ID` (`CATALOG_ID`),
  CONSTRAINT `cattogrp_ibfk_1` FOREIGN KEY (`CATGROUP_ID`) REFERENCES `catgroup` (`CATGROUP_ID`),
  CONSTRAINT `cattogrp_ibfk_2` FOREIGN KEY (`CATALOG_ID`) REFERENCES `catalog` (`CATALOG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `checkout` */

DROP TABLE IF EXISTS `checkout`;

CREATE TABLE `checkout` (
  `CHECKOUT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TIMEPLACED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTUPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` char(11) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `ORDERS_ID` bigint(20) NOT NULL,
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(254) DEFAULT NULL,
  PRIMARY KEY (`CHECKOUT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `orders` */

DROP TABLE IF EXISTS `orders`;

CREATE TABLE `orders` (
  `ORDERS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TOTALPRODUCT` decimal(20,5) NOT NULL,
  `TOTALTAX` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `DESCRIPTION` varchar(254) DEFAULT NULL,
  `TIMEPLACED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTUPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` char(3) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `TOTALADJUSTMENT` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `CSR_USER_ID` bigint(20) DEFAULT NULL,
  `EXPIREDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(254) DEFAULT NULL,
  PRIMARY KEY (`ORDERS_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `suborders` */

DROP TABLE IF EXISTS `suborders`;

CREATE TABLE `suborders` (
  `SUBORDERS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORDERS_ID` bigint(20) NOT NULL,
  `TOTALPRODUCT` decimal(20,5) NOT NULL,
  `TOTALTAX` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `CURRENCY` char(10) DEFAULT NULL,
  `DESCRIPTION` varchar(254) DEFAULT NULL,
  `TIMEPLACED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `LASTUPDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS` char(3) NOT NULL,
  `USER_ID` bigint(20) NOT NULL,
  `TOTALADJUSTMENT` decimal(20,5) NOT NULL DEFAULT '0.00000',
  `EXPIREDATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `FIELD1` int(11) DEFAULT NULL,
  `FIELD2` varchar(128) DEFAULT NULL,
  `FIELD3` varchar(254) DEFAULT NULL,
  PRIMARY KEY (`SUBORDERS_ID`),
  KEY `ORDERS_ID` (`ORDERS_ID`),
  KEY `USER_ID` (`USER_ID`),
  CONSTRAINT `suborders_ibfk_1` FOREIGN KEY (`ORDERS_ID`) REFERENCES `orders` (`ORDERS_ID`),
  CONSTRAINT `suborders_ibfk_2` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `user` */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `user_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(126) NOT NULL,
  `PASSWORD` varchar(126) NOT NULL,
  `EMAIL` varchar(126) DEFAULT NULL,
  `FIRST_NAME` varchar(126) DEFAULT NULL,
  `LAST_NAME` varchar(126) DEFAULT NULL,
  `GENDER` varchar(50) DEFAULT NULL,
  `STATUS` varchar(10) DEFAULT NULL,
  `DATE_OF_BIRTH` date DEFAULT NULL,
  `CREATED_TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `UPDATED_DATE_TIME` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
