package com.lcoperator.lcodb.model;
// Generated Mar 26, 2019 11:21:18 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catgroup generated by hbm2java
 */
@Entity
@Table(name = "catgroup", catalog = "lco_db")
public class Catgroup implements java.io.Serializable {

	private Long catgroupId;
	private String name;
	private String description;
	private String longdescription;
	private String thumbnail;
	private String fullimage;
	private int markfordelete;
	private Date lastupdate;
	private Integer field1;
	private String field2;
	private String field3;
	private Set<Cattogrp> cattogrps = new HashSet<Cattogrp>(0);
	private Set<Catgpenrel> catgpenrels = new HashSet<Catgpenrel>(0);

	public Catgroup() {
	}

	public Catgroup(String name, int markfordelete, Date lastupdate) {
		this.name = name;
		this.markfordelete = markfordelete;
		this.lastupdate = lastupdate;
	}

	public Catgroup(String name, String description, String longdescription, String thumbnail, String fullimage,
			int markfordelete, Date lastupdate, Integer field1, String field2, String field3, Set<Cattogrp> cattogrps,
			Set<Catgpenrel> catgpenrels) {
		this.name = name;
		this.description = description;
		this.longdescription = longdescription;
		this.thumbnail = thumbnail;
		this.fullimage = fullimage;
		this.markfordelete = markfordelete;
		this.lastupdate = lastupdate;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
		this.cattogrps = cattogrps;
		this.catgpenrels = catgpenrels;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "CATGROUP_ID", unique = true, nullable = false)
	public Long getCatgroupId() {
		return this.catgroupId;
	}

	public void setCatgroupId(Long catgroupId) {
		this.catgroupId = catgroupId;
	}

	@Column(name = "NAME", nullable = false, length = 254)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "LONGDESCRIPTION", length = 512)
	public String getLongdescription() {
		return this.longdescription;
	}

	public void setLongdescription(String longdescription) {
		this.longdescription = longdescription;
	}

	@Column(name = "THUMBNAIL", length = 254)
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@Column(name = "FULLIMAGE", length = 254)
	public String getFullimage() {
		return this.fullimage;
	}

	public void setFullimage(String fullimage) {
		this.fullimage = fullimage;
	}

	@Column(name = "MARKFORDELETE", nullable = false)
	public int getMarkfordelete() {
		return this.markfordelete;
	}

	public void setMarkfordelete(int markfordelete) {
		this.markfordelete = markfordelete;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE", nullable = false, length = 19)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 256)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catgroup")
	public Set<Cattogrp> getCattogrps() {
		return this.cattogrps;
	}

	public void setCattogrps(Set<Cattogrp> cattogrps) {
		this.cattogrps = cattogrps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catgroup")
	public Set<Catgpenrel> getCatgpenrels() {
		return this.catgpenrels;
	}

	public void setCatgpenrels(Set<Catgpenrel> catgpenrels) {
		this.catgpenrels = catgpenrels;
	}

}
