package com.lcoperator.lcodb.model;
// Generated Mar 26, 2019 11:21:18 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CattogrpId generated by hbm2java
 */
@Embeddable
public class CattogrpId implements java.io.Serializable {

	private long catgroupId;
	private long catalogId;
	private Integer field1;
	private String field2;

	public CattogrpId() {
	}

	public CattogrpId(long catgroupId, long catalogId) {
		this.catgroupId = catgroupId;
		this.catalogId = catalogId;
	}

	public CattogrpId(long catgroupId, long catalogId, Integer field1, String field2) {
		this.catgroupId = catgroupId;
		this.catalogId = catalogId;
		this.field1 = field1;
		this.field2 = field2;
	}

	@Column(name = "CATGROUP_ID", nullable = false)
	public long getCatgroupId() {
		return this.catgroupId;
	}

	public void setCatgroupId(long catgroupId) {
		this.catgroupId = catgroupId;
	}

	@Column(name = "CATALOG_ID", nullable = false)
	public long getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(long catalogId) {
		this.catalogId = catalogId;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CattogrpId))
			return false;
		CattogrpId castOther = (CattogrpId) other;

		return (this.getCatgroupId() == castOther.getCatgroupId()) && (this.getCatalogId() == castOther.getCatalogId())
				&& ((this.getField1() == castOther.getField1()) || (this.getField1() != null
						&& castOther.getField1() != null && this.getField1().equals(castOther.getField1())))
				&& ((this.getField2() == castOther.getField2()) || (this.getField2() != null
						&& castOther.getField2() != null && this.getField2().equals(castOther.getField2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCatgroupId();
		result = 37 * result + (int) this.getCatalogId();
		result = 37 * result + (getField1() == null ? 0 : this.getField1().hashCode());
		result = 37 * result + (getField2() == null ? 0 : this.getField2().hashCode());
		return result;
	}

}
