package com.lcoperator.lcodb.model;
// Generated Apr 9, 2019 6:17:37 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Checkout generated by hbm2java
 */
@Entity
@Table(name = "checkout", catalog = "lco_db")
public class Checkout implements java.io.Serializable {

	private Long checkoutId;
	private Date timeplaced;
	private Date lastupdate;
	private String status;
	private long userId;
	private long ordersId;
	private Integer field1;
	private String field2;
	private String field3;

	public Checkout() {
	}

	public Checkout(Date timeplaced, Date lastupdate, String status, long userId, long ordersId) {
		this.timeplaced = timeplaced;
		this.lastupdate = lastupdate;
		this.status = status;
		this.userId = userId;
		this.ordersId = ordersId;
	}

	public Checkout(Date timeplaced, Date lastupdate, String status, long userId, long ordersId, Integer field1,
			String field2, String field3) {
		this.timeplaced = timeplaced;
		this.lastupdate = lastupdate;
		this.status = status;
		this.userId = userId;
		this.ordersId = ordersId;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CHECKOUT_ID", unique = true, nullable = false)
	public Long getCheckoutId() {
		return this.checkoutId;
	}

	public void setCheckoutId(Long checkoutId) {
		this.checkoutId = checkoutId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMEPLACED", nullable = false, length = 19)
	public Date getTimeplaced() {
		return this.timeplaced;
	}

	public void setTimeplaced(Date timeplaced) {
		this.timeplaced = timeplaced;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE", nullable = false, length = 19)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Column(name = "STATUS", nullable = false, length = 11)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "USER_ID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "ORDERS_ID", nullable = false)
	public long getOrdersId() {
		return this.ordersId;
	}

	public void setOrdersId(long ordersId) {
		this.ordersId = ordersId;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 254)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

}
