package com.lcoperator.model;
// Generated Mar 26, 2019 11:21:18 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatgpenrelId generated by hbm2java
 */
@Embeddable
public class CatgpenrelId implements java.io.Serializable {

	private long catgroupId;
	private long catentryId;
	private long catalogId;

	public CatgpenrelId() {
	}

	public CatgpenrelId(long catgroupId, long catentryId, long catalogId) {
		this.catgroupId = catgroupId;
		this.catentryId = catentryId;
		this.catalogId = catalogId;
	}

	@Column(name = "CATGROUP_ID", nullable = false)
	public long getCatgroupId() {
		return this.catgroupId;
	}

	public void setCatgroupId(long catgroupId) {
		this.catgroupId = catgroupId;
	}

	@Column(name = "CATENTRY_ID", nullable = false)
	public long getCatentryId() {
		return this.catentryId;
	}

	public void setCatentryId(long catentryId) {
		this.catentryId = catentryId;
	}

	@Column(name = "CATALOG_ID", nullable = false)
	public long getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(long catalogId) {
		this.catalogId = catalogId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatgpenrelId))
			return false;
		CatgpenrelId castOther = (CatgpenrelId) other;

		return (this.getCatgroupId() == castOther.getCatgroupId())
				&& (this.getCatentryId() == castOther.getCatentryId())
				&& (this.getCatalogId() == castOther.getCatalogId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCatgroupId();
		result = 37 * result + (int) this.getCatentryId();
		result = 37 * result + (int) this.getCatalogId();
		return result;
	}

}
