package com.lcoperator.model;
// Generated Mar 26, 2019 11:21:18 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cattogrp generated by hbm2java
 */
@Entity
@Table(name = "cattogrp", catalog = "lco_db")
public class Cattogrp implements java.io.Serializable {

	private CattogrpId id;
	private Catalog catalog;
	private Catgroup catgroup;

	public Cattogrp() {
	}

	public Cattogrp(CattogrpId id, Catalog catalog, Catgroup catgroup) {
		this.id = id;
		this.catalog = catalog;
		this.catgroup = catgroup;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "catgroupId", column = @Column(name = "CATGROUP_ID", nullable = false)),
			@AttributeOverride(name = "catalogId", column = @Column(name = "CATALOG_ID", nullable = false)),
			@AttributeOverride(name = "field1", column = @Column(name = "FIELD1")),
			@AttributeOverride(name = "field2", column = @Column(name = "FIELD2", length = 128)) })
	public CattogrpId getId() {
		return this.id;
	}

	public void setId(CattogrpId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATALOG_ID", nullable = false, insertable = false, updatable = false)
	public Catalog getCatalog() {
		return this.catalog;
	}

	public void setCatalog(Catalog catalog) {
		this.catalog = catalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATGROUP_ID", nullable = false, insertable = false, updatable = false)
	public Catgroup getCatgroup() {
		return this.catgroup;
	}

	public void setCatgroup(Catgroup catgroup) {
		this.catgroup = catgroup;
	}

}
