package com.lcoperator.model;
// Generated Mar 26, 2019 11:21:18 PM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Suborders generated by hbm2java
 */
@Entity
@Table(name = "suborders", catalog = "lco_db")
public class Suborders implements java.io.Serializable {

	private Long subordersId;
	private Orders orders;
	private User user;
	private BigDecimal totalproduct;
	private BigDecimal totaltax;
	private String currency;
	private String description;
	private Date timeplaced;
	private Date lastupdate;
	private String status;
	private BigDecimal totaladjustment;
	private Date expiredate;
	private Integer field1;
	private String field2;
	private String field3;

	public Suborders() {
	}

	public Suborders(Orders orders, User user, BigDecimal totalproduct, BigDecimal totaltax, Date timeplaced,
			Date lastupdate, String status, BigDecimal totaladjustment, Date expiredate) {
		this.orders = orders;
		this.user = user;
		this.totalproduct = totalproduct;
		this.totaltax = totaltax;
		this.timeplaced = timeplaced;
		this.lastupdate = lastupdate;
		this.status = status;
		this.totaladjustment = totaladjustment;
		this.expiredate = expiredate;
	}

	public Suborders(Orders orders, User user, BigDecimal totalproduct, BigDecimal totaltax, String currency,
			String description, Date timeplaced, Date lastupdate, String status, BigDecimal totaladjustment,
			Date expiredate, Integer field1, String field2, String field3) {
		this.orders = orders;
		this.user = user;
		this.totalproduct = totalproduct;
		this.totaltax = totaltax;
		this.currency = currency;
		this.description = description;
		this.timeplaced = timeplaced;
		this.lastupdate = lastupdate;
		this.status = status;
		this.totaladjustment = totaladjustment;
		this.expiredate = expiredate;
		this.field1 = field1;
		this.field2 = field2;
		this.field3 = field3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SUBORDERS_ID", unique = true, nullable = false)
	public Long getSubordersId() {
		return this.subordersId;
	}

	public void setSubordersId(Long subordersId) {
		this.subordersId = subordersId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDERS_ID", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "TOTALPRODUCT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotalproduct() {
		return this.totalproduct;
	}

	public void setTotalproduct(BigDecimal totalproduct) {
		this.totalproduct = totalproduct;
	}

	@Column(name = "TOTALTAX", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotaltax() {
		return this.totaltax;
	}

	public void setTotaltax(BigDecimal totaltax) {
		this.totaltax = totaltax;
	}

	@Column(name = "CURRENCY", length = 10)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "DESCRIPTION", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMEPLACED", nullable = false, length = 19)
	public Date getTimeplaced() {
		return this.timeplaced;
	}

	public void setTimeplaced(Date timeplaced) {
		this.timeplaced = timeplaced;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTUPDATE", nullable = false, length = 19)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Column(name = "STATUS", nullable = false, length = 3)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "TOTALADJUSTMENT", nullable = false, precision = 20, scale = 5)
	public BigDecimal getTotaladjustment() {
		return this.totaladjustment;
	}

	public void setTotaladjustment(BigDecimal totaladjustment) {
		this.totaladjustment = totaladjustment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXPIREDATE", nullable = false, length = 19)
	public Date getExpiredate() {
		return this.expiredate;
	}

	public void setExpiredate(Date expiredate) {
		this.expiredate = expiredate;
	}

	@Column(name = "FIELD1")
	public Integer getField1() {
		return this.field1;
	}

	public void setField1(Integer field1) {
		this.field1 = field1;
	}

	@Column(name = "FIELD2", length = 128)
	public String getField2() {
		return this.field2;
	}

	public void setField2(String field2) {
		this.field2 = field2;
	}

	@Column(name = "FIELD3", length = 254)
	public String getField3() {
		return this.field3;
	}

	public void setField3(String field3) {
		this.field3 = field3;
	}

}
